---
title: "First simple hierarchical model - with exact GPR and two levels"
author: "Astrid Tausen"
date: today
format: html
execute:
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load-packages
library(here)
library(stringr)
library(cmdstanr)
```

```{r}
#| label: configuration

# Model identification:
data_file_name <- "xxxx.rds" # Choose right file here, begins with stan_list_2_level_
data_id <- str_extract(data_file_name, "\\d{8}_\\d{6}") # Get data timestamp

stan_file_name <- "cholesky_exact_gpr_2_level.stan"
model_type <- str_remove(stan_file_name, "\\.stan$")
run_id <- format(Sys.time(), "%Y%m%d_%H%M%S") # Generate run timestamp

# Paths:
path_processed <- here("data", "processed")
path_stan      <- here("stan")
path_results   <- here("data", "results")

if (!dir.exists(path_results)) {
  dir.create(path_results, recursive = TRUE)
}

# I should add parameters and priors here instead of hardcoding them in the stan model, I think 
# Could also have option to choose between linear and constant mean trend here - right now it's just constant

```

```{r}
#| label: load-data
dat_list <- readRDS(here(path_processed, data_file_name))
```

```{r}
#| label: compile-model
mod <- cmdstan_model(here(path_stan, stan_file_name))
```


```{r}
#| label: sample-prior-measure

dat_list$prior_only <- 1 

fit_prior <- mod$sample(
  data = dat_list,
  chains = 4,
  parallel_chains = 4, 
  iter_warmup = 1000,
  iter_sampling = 1000,
  seed = 1045,
  refresh = 500
)

output_name_prior <- paste0("prior_", model_type, "_data_", data_id, "run", run_id, ".rds")
fit_prior$save_object(here(path_results, output_name_prior))
```

```{r}
#| label: sample-posterior-measure

dat_list$prior_only <- 0 

fit_posterior <- mod$sample(
  data = dat_list,
  chains = 4,
  parallel_chains = 4, 
  iter_warmup = 1000,
  iter_sampling = 1000,
  seed = 1045,
  adapt_delta = 0.90, 
  max_treedepth = 11,
  refresh = 500,
  save_cmdstan_config = TRUE
)

output_name_posterior <- paste0("posterior_", model_type, "_data_", data_id, "_run_", run_id, ".rds")
fit_posterior$save_object(here(path_results, output_name_posterior))
```
